### ISSUE TITLE
Some text is hard to see against the background

### ISSUE THREAD

**Issue by maillouxc** [maillouxc/git-rekt#104]
Solution unknown, but the CSS styling should be tweaked in some way to make text, especially text lower on the screen, easier to see.

Talk to me, and the UI lead, before taking on this issue. You'll have to be a little creative to solve this.

This isn't a very high priority issue at the moment.

**Comment by Jgomez95** [comment]
When trying to create a new user, the red text that checks password validation is hard to read on the gradient backroom.
