### ISSUE TITLE
Prototype Leave Feedback Screen

### ISSUE THREAD

**Issue by maillouxc** [maillouxc/git-rekt#24]
Build a prototype of the screen that will allow the customer to leave feedback about the resort.

Don't worry about wiring it into the program logic. Just build the FXML layout using the Scene Builder. (Do the FXMLDocumentController with empty method stubs for any button clicks and such required by the form, if you can. If not, no big deal.) Also create any FX-CSS styles if you need to.

The screen should contain at minimum a text box for entering feedback, plus a submit button and a back or  cancel button. Exact layout is up to you. Styling is not super important (as in fonts, colors, etc.) but design is.

This should be a simple task, and is a good opportunity for people to get used to using JavaFX and working in a team programming workflow using tools like Git.

I would like for this issue to be finished by Friday night (10/11/2017), if possible.

This may end up being implemented as a Dialog, so consider using a dialog layout in your design of it. Play with it and see what works. This is an opportunity to exercise judgement and design skills.

**Comment by jfleurent** [comment]
I think I've uploaded something for this issue. Check to see if you can.
