### ISSUE TITLE
Write Room Class

### ISSUE THREAD

**Issue by maillouxc** [maillouxc/git-rekt#99]
See the UML diagrams shared in slack for details on this class.

Be sure to contact me before you begin work, just in case anything has changed.

**Comment by Daniel-GabrielN** [comment]
Hi Christopher, would be nice to add the diagrams here.

**Comment by maillouxc** [comment]
Haha, sorry, can't do that. This is a course project repository at the moment, so we can't currently accept outside contributions. (As much as that would make our life easier)

**Comment by maillouxc** [comment]
That said, if this repository does become open for public contributions at a later date, I'll be sure to do so.

**Comment by Daniel-GabrielN** [comment]
OK, good luck :D

**Comment by maillouxc** [comment]
I may have you write a commit for something simple at some point, lol. The opportunity for laughs is too good to pass up.

I can see it now; we'll just casually include your name in the credits for our final presentation and let the confusion ensue.

**Comment by maillouxc** [comment]
@Daniel-GabrielN Feel like doing something easy? Issue #73 would be super easy. It'd be pretty funny to have your name on our contributor's list.

**Comment by Daniel-GabrielN** [comment]
@maillouxc I will have a look tomorrow

**Comment by maillouxc** [comment]
@Daniel-GabrielN Haha, perfect. Cheers mate
